//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\g\hvc.DynamoDBReport\hvc.DynamoDBReport.Parser\Antlr4\DynamoDBReportAntlrLexer.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class DynamoDBReportAntlrLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQ=1, NEQ=2, LTE=3, LT=4, GTE=5, GT=6, AND=7, ASCENDING=8, BEGINS=9, BETWEEN=10, 
		CONTAINS=11, DESCENDING=12, EXISTS=13, FILTERS=14, FROM=15, KEY=16, NOT=17, 
		REPORT=18, SELECT=19, USING=20, WHERE=21, WITH=22, COMMA=23, COLUMN=24, 
		EQUAL=25, SEMICOLUMN=26, BEGIN_BLOCK=27, END_BLOCK=28, OPEN_PARA=29, CLOSE_PARA=30, 
		STRING_WITH_QUOTES=31, SPACE=32, COMMENT=33, IDENTIFIER=34;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"EQ", "NEQ", "LTE", "LT", "GTE", "GT", "AND", "ASCENDING", "BEGINS", "BETWEEN", 
		"CONTAINS", "DESCENDING", "EXISTS", "FILTERS", "FROM", "KEY", "NOT", "REPORT", 
		"SELECT", "USING", "WHERE", "WITH", "COMMA", "COLUMN", "EQUAL", "SEMICOLUMN", 
		"BEGIN_BLOCK", "END_BLOCK", "OPEN_PARA", "CLOSE_PARA", "STRING_WITH_QUOTES", 
		"SPACE", "COMMENT", "IDENTIFIER"
	};


	public DynamoDBReportAntlrLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DynamoDBReportAntlrLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'=='", "'!='", "'<='", "'<'", "'>='", "'>'", "'And'", "'Ascending'", 
		"'Begins'", "'Between'", "'Contains'", "'Descending'", "'Exists'", "'Filters'", 
		"'From'", "'Key'", "'Not'", "'Report'", "'Select'", "'Using'", "'Where'", 
		"'With'", "','", "':'", "'='", "';'", "'{'", "'}'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQ", "NEQ", "LTE", "LT", "GTE", "GT", "AND", "ASCENDING", "BEGINS", 
		"BETWEEN", "CONTAINS", "DESCENDING", "EXISTS", "FILTERS", "FROM", "KEY", 
		"NOT", "REPORT", "SELECT", "USING", "WHERE", "WITH", "COMMA", "COLUMN", 
		"EQUAL", "SEMICOLUMN", "BEGIN_BLOCK", "END_BLOCK", "OPEN_PARA", "CLOSE_PARA", 
		"STRING_WITH_QUOTES", "SPACE", "COMMENT", "IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DynamoDBReportAntlrLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DynamoDBReportAntlrLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '$', '\x108', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\a', ' ', '\xD6', '\n', ' ', '\f', 
		' ', '\xE', ' ', '\xD9', '\v', ' ', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x6', '!', '\xDE', '\n', '!', '\r', '!', '\xE', '!', '\xDF', '\x3', '!', 
		'\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\a', 
		'\"', '\xE8', '\n', '\"', '\f', '\"', '\xE', '\"', '\xEB', '\v', '\"', 
		'\x3', '\"', '\x5', '\"', '\xEE', '\n', '\"', '\x3', '\"', '\x3', '\"', 
		'\x3', '\"', '\x3', '\"', '\x3', '\"', '\a', '\"', '\xF5', '\n', '\"', 
		'\f', '\"', '\xE', '\"', '\xF8', '\v', '\"', '\x3', '\"', '\x3', '\"', 
		'\x5', '\"', '\xFC', '\n', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', 
		'\x5', '#', '\x101', '\n', '#', '\x3', '#', '\a', '#', '\x104', '\n', 
		'#', '\f', '#', '\xE', '#', '\x107', '\v', '#', '\x3', '\xF6', '\x2', 
		'$', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', 
		'-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', 
		'\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', 
		'\"', '\x43', '#', '\x45', '$', '\x3', '\x2', '\a', '\x6', '\x2', '\f', 
		'\f', '\xE', '\xF', ')', ')', '^', '^', '\x5', '\x2', '\v', '\f', '\xF', 
		'\xF', '\"', '\"', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x4', '\x2', 
		'\x43', '\\', '\x63', '|', '\a', '\x2', '/', '/', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x2', '\x10E', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', 
		'\x2', '\x2', '\x3', 'G', '\x3', '\x2', '\x2', '\x2', '\x5', 'J', '\x3', 
		'\x2', '\x2', '\x2', '\a', 'M', '\x3', '\x2', '\x2', '\x2', '\t', 'P', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'R', '\x3', '\x2', '\x2', '\x2', '\r', 
		'U', '\x3', '\x2', '\x2', '\x2', '\xF', 'W', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '[', '\x3', '\x2', '\x2', '\x2', '\x13', '\x65', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'l', '\x3', '\x2', '\x2', '\x2', '\x17', 't', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '}', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x97', '\x3', '\x2', '\x2', '\x2', '!', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '#', '\xA0', '\x3', '\x2', '\x2', '\x2', '%', '\xA4', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\xAB', '\x3', '\x2', '\x2', '\x2', 
		')', '\xB2', '\x3', '\x2', '\x2', '\x2', '+', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '-', '\xBE', '\x3', '\x2', '\x2', '\x2', '/', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\xC5', '\x3', '\x2', '\x2', '\x2', '\x33', '\xC7', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xCB', '\x3', '\x2', '\x2', '\x2', '\x39', '\xCD', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xCF', '\x3', '\x2', '\x2', '\x2', '=', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '?', '\xD3', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xDD', '\x3', '\x2', '\x2', '\x2', '\x43', '\xFB', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x100', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '?', 
		'\x2', '\x2', 'H', 'I', '\a', '?', '\x2', '\x2', 'I', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'K', '\a', '#', '\x2', '\x2', 'K', 'L', '\a', '?', 
		'\x2', '\x2', 'L', '\x6', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 
		'>', '\x2', '\x2', 'N', 'O', '\a', '?', '\x2', '\x2', 'O', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'Q', '\a', '>', '\x2', '\x2', 'Q', '\n', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'S', '\a', '@', '\x2', '\x2', 'S', 'T', '\a', 
		'?', '\x2', '\x2', 'T', '\f', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', 
		'@', '\x2', '\x2', 'V', '\xE', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 
		'\x43', '\x2', '\x2', 'X', 'Y', '\a', 'p', '\x2', '\x2', 'Y', 'Z', '\a', 
		'\x66', '\x2', '\x2', 'Z', '\x10', '\x3', '\x2', '\x2', '\x2', '[', '\\', 
		'\a', '\x43', '\x2', '\x2', '\\', ']', '\a', 'u', '\x2', '\x2', ']', '^', 
		'\a', '\x65', '\x2', '\x2', '^', '_', '\a', 'g', '\x2', '\x2', '_', '`', 
		'\a', 'p', '\x2', '\x2', '`', '\x61', '\a', '\x66', '\x2', '\x2', '\x61', 
		'\x62', '\a', 'k', '\x2', '\x2', '\x62', '\x63', '\a', 'p', '\x2', '\x2', 
		'\x63', '\x64', '\a', 'i', '\x2', '\x2', '\x64', '\x12', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\x66', '\a', '\x44', '\x2', '\x2', '\x66', 'g', 
		'\a', 'g', '\x2', '\x2', 'g', 'h', '\a', 'i', '\x2', '\x2', 'h', 'i', 
		'\a', 'k', '\x2', '\x2', 'i', 'j', '\a', 'p', '\x2', '\x2', 'j', 'k', 
		'\a', 'u', '\x2', '\x2', 'k', '\x14', '\x3', '\x2', '\x2', '\x2', 'l', 
		'm', '\a', '\x44', '\x2', '\x2', 'm', 'n', '\a', 'g', '\x2', '\x2', 'n', 
		'o', '\a', 'v', '\x2', '\x2', 'o', 'p', '\a', 'y', '\x2', '\x2', 'p', 
		'q', '\a', 'g', '\x2', '\x2', 'q', 'r', '\a', 'g', '\x2', '\x2', 'r', 
		's', '\a', 'p', '\x2', '\x2', 's', '\x16', '\x3', '\x2', '\x2', '\x2', 
		't', 'u', '\a', '\x45', '\x2', '\x2', 'u', 'v', '\a', 'q', '\x2', '\x2', 
		'v', 'w', '\a', 'p', '\x2', '\x2', 'w', 'x', '\a', 'v', '\x2', '\x2', 
		'x', 'y', '\a', '\x63', '\x2', '\x2', 'y', 'z', '\a', 'k', '\x2', '\x2', 
		'z', '{', '\a', 'p', '\x2', '\x2', '{', '|', '\a', 'u', '\x2', '\x2', 
		'|', '\x18', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', '\x46', '\x2', 
		'\x2', '~', '\x7F', '\a', 'g', '\x2', '\x2', '\x7F', '\x80', '\a', 'u', 
		'\x2', '\x2', '\x80', '\x81', '\a', '\x65', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'g', '\x2', '\x2', '\x82', '\x83', '\a', 'p', '\x2', '\x2', '\x83', 
		'\x84', '\a', '\x66', '\x2', '\x2', '\x84', '\x85', '\a', 'k', '\x2', 
		'\x2', '\x85', '\x86', '\a', 'p', '\x2', '\x2', '\x86', '\x87', '\a', 
		'i', '\x2', '\x2', '\x87', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'G', '\x2', '\x2', '\x89', '\x8A', '\a', 'z', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', 'k', '\x2', '\x2', '\x8B', '\x8C', '\a', 'u', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', 'v', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'u', '\x2', '\x2', '\x8E', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x90', '\a', 'H', '\x2', '\x2', '\x90', '\x91', '\a', 'k', '\x2', '\x2', 
		'\x91', '\x92', '\a', 'n', '\x2', '\x2', '\x92', '\x93', '\a', 'v', '\x2', 
		'\x2', '\x93', '\x94', '\a', 'g', '\x2', '\x2', '\x94', '\x95', '\a', 
		't', '\x2', '\x2', '\x95', '\x96', '\a', 'u', '\x2', '\x2', '\x96', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\a', 'H', '\x2', '\x2', '\x98', 
		'\x99', '\a', 't', '\x2', '\x2', '\x99', '\x9A', '\a', 'q', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', 'o', '\x2', '\x2', '\x9B', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\a', 'M', '\x2', '\x2', '\x9D', '\x9E', '\a', 
		'g', '\x2', '\x2', '\x9E', '\x9F', '\a', '{', '\x2', '\x2', '\x9F', '\"', 
		'\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', 'P', '\x2', '\x2', '\xA1', 
		'\xA2', '\a', 'q', '\x2', '\x2', '\xA2', '\xA3', '\a', 'v', '\x2', '\x2', 
		'\xA3', '$', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 'T', '\x2', 
		'\x2', '\xA5', '\xA6', '\a', 'g', '\x2', '\x2', '\xA6', '\xA7', '\a', 
		'r', '\x2', '\x2', '\xA7', '\xA8', '\a', 'q', '\x2', '\x2', '\xA8', '\xA9', 
		'\a', 't', '\x2', '\x2', '\xA9', '\xAA', '\a', 'v', '\x2', '\x2', '\xAA', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\a', 'U', '\x2', '\x2', 
		'\xAC', '\xAD', '\a', 'g', '\x2', '\x2', '\xAD', '\xAE', '\a', 'n', '\x2', 
		'\x2', '\xAE', '\xAF', '\a', 'g', '\x2', '\x2', '\xAF', '\xB0', '\a', 
		'\x65', '\x2', '\x2', '\xB0', '\xB1', '\a', 'v', '\x2', '\x2', '\xB1', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', 'W', '\x2', '\x2', 
		'\xB3', '\xB4', '\a', 'u', '\x2', '\x2', '\xB4', '\xB5', '\a', 'k', '\x2', 
		'\x2', '\xB5', '\xB6', '\a', 'p', '\x2', '\x2', '\xB6', '\xB7', '\a', 
		'i', '\x2', '\x2', '\xB7', '*', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', 'Y', '\x2', '\x2', '\xB9', '\xBA', '\a', 'j', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', 'g', '\x2', '\x2', '\xBB', '\xBC', '\a', 't', '\x2', '\x2', 
		'\xBC', '\xBD', '\a', 'g', '\x2', '\x2', '\xBD', ',', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBF', '\a', 'Y', '\x2', '\x2', '\xBF', '\xC0', '\a', 
		'k', '\x2', '\x2', '\xC0', '\xC1', '\a', 'v', '\x2', '\x2', '\xC1', '\xC2', 
		'\a', 'j', '\x2', '\x2', '\xC2', '.', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC4', '\a', '.', '\x2', '\x2', '\xC4', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC6', '\a', '<', '\x2', '\x2', '\xC6', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', '\xC8', '\a', '?', '\x2', '\x2', '\xC8', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', '\a', '=', '\x2', 
		'\x2', '\xCA', '\x36', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', 
		'}', '\x2', '\x2', '\xCC', '\x38', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCE', '\a', '\x7F', '\x2', '\x2', '\xCE', ':', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD0', '\a', '*', '\x2', '\x2', '\xD0', '<', '\x3', '\x2', 
		'\x2', '\x2', '\xD1', '\xD2', '\a', '+', '\x2', '\x2', '\xD2', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD7', '\a', ')', '\x2', '\x2', '\xD4', 
		'\xD6', '\n', '\x2', '\x2', '\x2', '\xD5', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\xD6', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD5', '\x3', 
		'\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xD8', 
		'\xDA', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xD7', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xDB', '\a', ')', '\x2', '\x2', '\xDB', '@', '\x3', '\x2', 
		'\x2', '\x2', '\xDC', '\xDE', '\t', '\x3', '\x2', '\x2', '\xDD', '\xDC', 
		'\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\x3', '\x2', '\x2', '\x2', 
		'\xDF', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', '\x3', '\x2', 
		'\x2', '\x2', '\xE0', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', 
		'\b', '!', '\x2', '\x2', '\xE2', '\x42', '\x3', '\x2', '\x2', '\x2', '\xE3', 
		'\xE4', '\a', '\x31', '\x2', '\x2', '\xE4', '\xE5', '\a', '\x31', '\x2', 
		'\x2', '\xE5', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE8', '\n', 
		'\x4', '\x2', '\x2', '\xE7', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xE7', '\x3', '\x2', '\x2', 
		'\x2', '\xE9', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xED', '\x3', 
		'\x2', '\x2', '\x2', '\xEB', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xEE', '\a', '\xF', '\x2', '\x2', '\xED', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', '\xED', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEF', '\x3', 
		'\x2', '\x2', '\x2', '\xEF', '\xFC', '\a', '\f', '\x2', '\x2', '\xF0', 
		'\xF1', '\a', '\x31', '\x2', '\x2', '\xF1', '\xF2', '\a', ',', '\x2', 
		'\x2', '\xF2', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF5', '\v', 
		'\x2', '\x2', '\x2', '\xF4', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF5', 
		'\xF8', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\x3', '\x2', '\x2', 
		'\x2', '\xF6', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF9', '\x3', 
		'\x2', '\x2', '\x2', '\xF8', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF9', 
		'\xFA', '\a', ',', '\x2', '\x2', '\xFA', '\xFC', '\a', '\x31', '\x2', 
		'\x2', '\xFB', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xF0', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\xFD', '\x3', '\x2', '\x2', '\x2', '\xFD', 
		'\xFE', '\b', '\"', '\x2', '\x2', '\xFE', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\xFF', '\x101', '\t', '\x5', '\x2', '\x2', '\x100', '\xFF', '\x3', 
		'\x2', '\x2', '\x2', '\x101', '\x105', '\x3', '\x2', '\x2', '\x2', '\x102', 
		'\x104', '\t', '\x6', '\x2', '\x2', '\x103', '\x102', '\x3', '\x2', '\x2', 
		'\x2', '\x104', '\x107', '\x3', '\x2', '\x2', '\x2', '\x105', '\x103', 
		'\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\x3', '\x2', '\x2', '\x2', 
		'\x106', '\x46', '\x3', '\x2', '\x2', '\x2', '\x107', '\x105', '\x3', 
		'\x2', '\x2', '\x2', '\f', '\x2', '\xD7', '\xDF', '\xE9', '\xED', '\xF6', 
		'\xFB', '\x100', '\x103', '\x105', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
