//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\g\hvc.DynamoDBReport\hvc.DynamoDBReport.Parser\Antlr4\DynamoDBReportAntlrParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDynamoDBReportAntlrParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DynamoDBReportAntlrParserBaseListener : IDynamoDBReportAntlrParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.start_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_rule([NotNull] DynamoDBReportAntlrParser.Start_ruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.start_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_rule([NotNull] DynamoDBReportAntlrParser.Start_ruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.dynamo_query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDynamo_query([NotNull] DynamoDBReportAntlrParser.Dynamo_queryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.dynamo_query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDynamo_query([NotNull] DynamoDBReportAntlrParser.Dynamo_queryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.report_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReport_name([NotNull] DynamoDBReportAntlrParser.Report_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.report_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReport_name([NotNull] DynamoDBReportAntlrParser.Report_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.select_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_statement([NotNull] DynamoDBReportAntlrParser.Select_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.select_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_statement([NotNull] DynamoDBReportAntlrParser.Select_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_name([NotNull] DynamoDBReportAntlrParser.Table_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_name([NotNull] DynamoDBReportAntlrParser.Table_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.output_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput_column([NotNull] DynamoDBReportAntlrParser.Output_columnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.output_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput_column([NotNull] DynamoDBReportAntlrParser.Output_columnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartition_statement([NotNull] DynamoDBReportAntlrParser.Partition_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartition_statement([NotNull] DynamoDBReportAntlrParser.Partition_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartition_key_name([NotNull] DynamoDBReportAntlrParser.Partition_key_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartition_key_name([NotNull] DynamoDBReportAntlrParser.Partition_key_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartition_key_value([NotNull] DynamoDBReportAntlrParser.Partition_key_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartition_key_value([NotNull] DynamoDBReportAntlrParser.Partition_key_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_statement([NotNull] DynamoDBReportAntlrParser.Index_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_statement([NotNull] DynamoDBReportAntlrParser.Index_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_name([NotNull] DynamoDBReportAntlrParser.Index_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_name([NotNull] DynamoDBReportAntlrParser.Index_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKey_statement([NotNull] DynamoDBReportAntlrParser.Key_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKey_statement([NotNull] DynamoDBReportAntlrParser.Key_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKey_name([NotNull] DynamoDBReportAntlrParser.Key_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKey_name([NotNull] DynamoDBReportAntlrParser.Key_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKey_statement_value([NotNull] DynamoDBReportAntlrParser.Key_statement_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKey_statement_value([NotNull] DynamoDBReportAntlrParser.Key_statement_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortkey_statement([NotNull] DynamoDBReportAntlrParser.Sortkey_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortkey_statement([NotNull] DynamoDBReportAntlrParser.Sortkey_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Simple_sortkey_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Simple_sortkey_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBetween_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Between_sortkey_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBetween_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Between_sortkey_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.beginswith_sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBeginswith_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Beginswith_sortkey_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.beginswith_sortkey_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBeginswith_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Beginswith_sortkey_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortkey_name([NotNull] DynamoDBReportAntlrParser.Sortkey_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortkey_name([NotNull] DynamoDBReportAntlrParser.Sortkey_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortkey_value([NotNull] DynamoDBReportAntlrParser.Sortkey_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortkey_value([NotNull] DynamoDBReportAntlrParser.Sortkey_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortkey_condition([NotNull] DynamoDBReportAntlrParser.Sortkey_conditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortkey_condition([NotNull] DynamoDBReportAntlrParser.Sortkey_conditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.where_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere_statement([NotNull] DynamoDBReportAntlrParser.Where_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.where_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere_statement([NotNull] DynamoDBReportAntlrParser.Where_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_filter_statement([NotNull] DynamoDBReportAntlrParser.Simple_filter_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_filter_statement([NotNull] DynamoDBReportAntlrParser.Simple_filter_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBetween_filter_statement([NotNull] DynamoDBReportAntlrParser.Between_filter_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBetween_filter_statement([NotNull] DynamoDBReportAntlrParser.Between_filter_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.exists_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExists_filter_statement([NotNull] DynamoDBReportAntlrParser.Exists_filter_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.exists_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExists_filter_statement([NotNull] DynamoDBReportAntlrParser.Exists_filter_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.contains_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContains_filter_statement([NotNull] DynamoDBReportAntlrParser.Contains_filter_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.contains_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContains_filter_statement([NotNull] DynamoDBReportAntlrParser.Contains_filter_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.begins_with_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBegins_with_filter_statement([NotNull] DynamoDBReportAntlrParser.Begins_with_filter_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.begins_with_filter_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBegins_with_filter_statement([NotNull] DynamoDBReportAntlrParser.Begins_with_filter_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter_name([NotNull] DynamoDBReportAntlrParser.Filter_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter_name([NotNull] DynamoDBReportAntlrParser.Filter_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter_condition([NotNull] DynamoDBReportAntlrParser.Filter_conditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter_condition([NotNull] DynamoDBReportAntlrParser.Filter_conditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] DynamoDBReportAntlrParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] DynamoDBReportAntlrParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.first_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirst_value([NotNull] DynamoDBReportAntlrParser.First_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.first_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirst_value([NotNull] DynamoDBReportAntlrParser.First_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.second_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSecond_value([NotNull] DynamoDBReportAntlrParser.Second_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.second_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSecond_value([NotNull] DynamoDBReportAntlrParser.Second_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.string_with_quotes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_with_quotes([NotNull] DynamoDBReportAntlrParser.String_with_quotesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.string_with_quotes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_with_quotes([NotNull] DynamoDBReportAntlrParser.String_with_quotesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] DynamoDBReportAntlrParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] DynamoDBReportAntlrParser.ParameterContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
