//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\g\hvc.DynamoDBReport\hvc.DynamoDBReport.Parser\Antlr4\DynamoDBReportAntlrParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DynamoDBReportAntlrParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IDynamoDBReportAntlrParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart_rule([NotNull] DynamoDBReportAntlrParser.Start_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.dynamo_query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamo_query([NotNull] DynamoDBReportAntlrParser.Dynamo_queryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.report_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReport_name([NotNull] DynamoDBReportAntlrParser.Report_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_statement([NotNull] DynamoDBReportAntlrParser.Select_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_name([NotNull] DynamoDBReportAntlrParser.Table_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.output_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_column([NotNull] DynamoDBReportAntlrParser.Output_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartition_statement([NotNull] DynamoDBReportAntlrParser.Partition_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartition_key_name([NotNull] DynamoDBReportAntlrParser.Partition_key_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartition_key_value([NotNull] DynamoDBReportAntlrParser.Partition_key_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_statement([NotNull] DynamoDBReportAntlrParser.Index_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_name([NotNull] DynamoDBReportAntlrParser.Index_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_statement([NotNull] DynamoDBReportAntlrParser.Key_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_name([NotNull] DynamoDBReportAntlrParser.Key_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_statement_value([NotNull] DynamoDBReportAntlrParser.Key_statement_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortkey_statement([NotNull] DynamoDBReportAntlrParser.Sortkey_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Simple_sortkey_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetween_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Between_sortkey_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.beginswith_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBeginswith_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Beginswith_sortkey_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortkey_name([NotNull] DynamoDBReportAntlrParser.Sortkey_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortkey_value([NotNull] DynamoDBReportAntlrParser.Sortkey_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortkey_condition([NotNull] DynamoDBReportAntlrParser.Sortkey_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.where_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_statement([NotNull] DynamoDBReportAntlrParser.Where_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_filter_statement([NotNull] DynamoDBReportAntlrParser.Simple_filter_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetween_filter_statement([NotNull] DynamoDBReportAntlrParser.Between_filter_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.exists_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExists_filter_statement([NotNull] DynamoDBReportAntlrParser.Exists_filter_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.contains_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContains_filter_statement([NotNull] DynamoDBReportAntlrParser.Contains_filter_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.begins_with_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBegins_with_filter_statement([NotNull] DynamoDBReportAntlrParser.Begins_with_filter_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_name([NotNull] DynamoDBReportAntlrParser.Filter_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_condition([NotNull] DynamoDBReportAntlrParser.Filter_conditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] DynamoDBReportAntlrParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.first_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirst_value([NotNull] DynamoDBReportAntlrParser.First_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.second_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecond_value([NotNull] DynamoDBReportAntlrParser.Second_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.string_with_quotes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_with_quotes([NotNull] DynamoDBReportAntlrParser.String_with_quotesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DynamoDBReportAntlrParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] DynamoDBReportAntlrParser.ParameterContext context);
}
