//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\g\hvc.DynamoDBReport\hvc.DynamoDBReport.Parser\Antlr4\DynamoDBReportAntlrParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DynamoDBReportAntlrParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IDynamoDBReportAntlrParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart_rule([NotNull] DynamoDBReportAntlrParser.Start_ruleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart_rule([NotNull] DynamoDBReportAntlrParser.Start_ruleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.dynamo_query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDynamo_query([NotNull] DynamoDBReportAntlrParser.Dynamo_queryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.dynamo_query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDynamo_query([NotNull] DynamoDBReportAntlrParser.Dynamo_queryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.report_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReport_name([NotNull] DynamoDBReportAntlrParser.Report_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.report_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReport_name([NotNull] DynamoDBReportAntlrParser.Report_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_statement([NotNull] DynamoDBReportAntlrParser.Select_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_statement([NotNull] DynamoDBReportAntlrParser.Select_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_name([NotNull] DynamoDBReportAntlrParser.Table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_name([NotNull] DynamoDBReportAntlrParser.Table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.output_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput_column([NotNull] DynamoDBReportAntlrParser.Output_columnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.output_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput_column([NotNull] DynamoDBReportAntlrParser.Output_columnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartition_statement([NotNull] DynamoDBReportAntlrParser.Partition_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartition_statement([NotNull] DynamoDBReportAntlrParser.Partition_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartition_key_name([NotNull] DynamoDBReportAntlrParser.Partition_key_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartition_key_name([NotNull] DynamoDBReportAntlrParser.Partition_key_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartition_key_value([NotNull] DynamoDBReportAntlrParser.Partition_key_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.partition_key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartition_key_value([NotNull] DynamoDBReportAntlrParser.Partition_key_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_statement([NotNull] DynamoDBReportAntlrParser.Index_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_statement([NotNull] DynamoDBReportAntlrParser.Index_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_name([NotNull] DynamoDBReportAntlrParser.Index_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_name([NotNull] DynamoDBReportAntlrParser.Index_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey_statement([NotNull] DynamoDBReportAntlrParser.Key_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey_statement([NotNull] DynamoDBReportAntlrParser.Key_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey_name([NotNull] DynamoDBReportAntlrParser.Key_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey_name([NotNull] DynamoDBReportAntlrParser.Key_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey_statement_value([NotNull] DynamoDBReportAntlrParser.Key_statement_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.key_statement_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey_statement_value([NotNull] DynamoDBReportAntlrParser.Key_statement_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortkey_statement([NotNull] DynamoDBReportAntlrParser.Sortkey_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortkey_statement([NotNull] DynamoDBReportAntlrParser.Sortkey_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Simple_sortkey_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Simple_sortkey_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBetween_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Between_sortkey_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBetween_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Between_sortkey_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.beginswith_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBeginswith_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Beginswith_sortkey_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.beginswith_sortkey_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBeginswith_sortkey_statement([NotNull] DynamoDBReportAntlrParser.Beginswith_sortkey_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortkey_name([NotNull] DynamoDBReportAntlrParser.Sortkey_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortkey_name([NotNull] DynamoDBReportAntlrParser.Sortkey_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortkey_value([NotNull] DynamoDBReportAntlrParser.Sortkey_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortkey_value([NotNull] DynamoDBReportAntlrParser.Sortkey_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortkey_condition([NotNull] DynamoDBReportAntlrParser.Sortkey_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.sortkey_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortkey_condition([NotNull] DynamoDBReportAntlrParser.Sortkey_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.where_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhere_statement([NotNull] DynamoDBReportAntlrParser.Where_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.where_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhere_statement([NotNull] DynamoDBReportAntlrParser.Where_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_filter_statement([NotNull] DynamoDBReportAntlrParser.Simple_filter_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.simple_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_filter_statement([NotNull] DynamoDBReportAntlrParser.Simple_filter_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBetween_filter_statement([NotNull] DynamoDBReportAntlrParser.Between_filter_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.between_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBetween_filter_statement([NotNull] DynamoDBReportAntlrParser.Between_filter_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.exists_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExists_filter_statement([NotNull] DynamoDBReportAntlrParser.Exists_filter_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.exists_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExists_filter_statement([NotNull] DynamoDBReportAntlrParser.Exists_filter_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.contains_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContains_filter_statement([NotNull] DynamoDBReportAntlrParser.Contains_filter_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.contains_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContains_filter_statement([NotNull] DynamoDBReportAntlrParser.Contains_filter_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.begins_with_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBegins_with_filter_statement([NotNull] DynamoDBReportAntlrParser.Begins_with_filter_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.begins_with_filter_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBegins_with_filter_statement([NotNull] DynamoDBReportAntlrParser.Begins_with_filter_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter_name([NotNull] DynamoDBReportAntlrParser.Filter_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter_name([NotNull] DynamoDBReportAntlrParser.Filter_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter_condition([NotNull] DynamoDBReportAntlrParser.Filter_conditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.filter_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter_condition([NotNull] DynamoDBReportAntlrParser.Filter_conditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] DynamoDBReportAntlrParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] DynamoDBReportAntlrParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.first_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFirst_value([NotNull] DynamoDBReportAntlrParser.First_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.first_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFirst_value([NotNull] DynamoDBReportAntlrParser.First_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.second_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecond_value([NotNull] DynamoDBReportAntlrParser.Second_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.second_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecond_value([NotNull] DynamoDBReportAntlrParser.Second_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.string_with_quotes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_with_quotes([NotNull] DynamoDBReportAntlrParser.String_with_quotesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.string_with_quotes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_with_quotes([NotNull] DynamoDBReportAntlrParser.String_with_quotesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DynamoDBReportAntlrParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] DynamoDBReportAntlrParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DynamoDBReportAntlrParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] DynamoDBReportAntlrParser.ParameterContext context);
}
